apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.5.0   
    helm:
      releaseName: kube-prometheus-stack
      valuesObject:
        grafana:
          enabled: true
          grafana.ini:
            server:
              domain: ac94a37a5ec8b4ad9b2774c4c18fec3c-340722538.eu-north-1.elb.amazonaws.com
              root_url: "%(protocol)s://%(domain)s/monitoring/"
              serve_from_sub_path: true
          admin:
            adminUser: admin
            adminPassword: prom-operator
          service:
            type: ClusterIP
            port: 80
          persistence:
            enabled: true            
            size: 5Gi
            storageClassName: gp2
          additionalDataSources:
            - name: Loki
              type: loki
              url: http://loki-stack.monitoring.svc.cluster.local:3100
              access: proxy
        prometheus:
          prometheusSpec:
            retention: 15d
            resources:
              requests:
                cpu: 250m
                memory: 512Mi
              limits:
                memory: 1Gi
        prometheusOperator:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true