apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: devboard-app
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  labels:
    apps: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      apps: backend
  template:
    metadata:
      labels:
        apps: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tags }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-sec
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-sec
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: pg-sec
                  key: POSTGRES_DB
            - name: PORT
              value: '8080'
            - name: POSTGRES_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)?sslmode=disable"
          {{- with .Values.backend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devboard-app
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
  labels:
    apps: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      apps: frontend
  template:
    metadata:
      labels:
        apps: frontend
    spec:
      containers:
        - name: frontend-devboard
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tags }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          