apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pg-sec
  namespace: devboard-app
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-3"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: pg-sec
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: devboard/postgres
        property: password
    - secretKey: POSTGRES_USER
      remoteRef:
        key: devboard/postgres
        property: username
    - secretKey: POSTGRES_DB
      remoteRef:
        key: devboard/postgres
        property: dbname