apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata: 
  name: envoy
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller

---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: devboard-gateway
  namespace: devboard-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  gatewayClassName: envoy
  listeners:
  - name: http
    protocol: {{.Values.gateway.protocol }}
    port: {{.Values.gateway.port }}
    allowedRoutes:
      namespaces:
        from: Same

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: devboard-route
  namespace: devboard-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parentRefs:
    - name: devboard-gateway
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: frontend-service
          port: {{.Values.gateway.port }}