
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  namespace: devboard-app
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  01_schema.sql: {{ .Values.config.schema | quote }}
  02_seed.sql: {{ .Values.config.seed | quote }}

  