apiVersion: v1
kind: Secret
metadata:
  name: pg-sec
  namespace: devboard-app
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  namespace: devboard-app
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  01_schema.sql: {{ .Values.config.schema | quote }}
  02_seed.sql: {{ .Values.config.seed | quote }}

  