apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devboard-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  type: {{ .Values.frontend.service.type }}     
  selector:
    apps: frontend   
  ports:
    - port: {{ .Values.frontend.service.lb }}
      targetPort: {{ .Values.frontend.service.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: devboard-app
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    apps: backend
  type: {{ .Values.backend.service.type }}        
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}

